# Generated by Django 5.2 on 2025-05-17 13:36

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介')),
                ('native_language', models.CharField(choices=[('japanese', '日本語'), ('english', '英語'), ('chinese', '中国語'), ('korean', '韓国語'), ('french', 'フランス語'), ('german', 'ドイツ語'), ('spanish', 'スペイン語'), ('other', 'その他')], default='japanese', max_length=50, verbose_name='母国語')),
                ('japanese_level', models.CharField(choices=[('none', '学習経験なし'), ('beginner', '少しわかる（初心者レベル）'), ('daily', '日常会話レベル'), ('business', 'ビジネスレベル'), ('native', 'ネイティブレベル')], default='none', max_length=20, verbose_name='日本語レベル')),
                ('english_level', models.CharField(choices=[('none', '学習経験なし'), ('beginner', '少しわかる（初心者レベル）'), ('daily', '日常会話レベル'), ('business', 'ビジネスレベル'), ('native', 'ネイティブレベル')], default='none', max_length=20, verbose_name='英語レベル')),
                ('is_japanese', models.BooleanField(default=True, verbose_name='日本人フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
