# Generated by Django 5.2 on 2025-05-17 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='common.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='common.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='photos_phot_user_id_f39ddb_idx'), models.Index(fields=['category'], name='photos_phot_categor_d05da2_idx'), models.Index(fields=['location_name'], name='photos_phot_locatio_bbe526_idx'), models.Index(fields=['created_at'], name='photos_phot_created_84134a_idx'), models.Index(fields=['latitude', 'longitude'], name='photos_phot_latitud_92201d_idx'), models.Index(fields=['slug'], name='photos_phot_slug_e8dac6_idx'), models.Index(fields=['is_published'], name='photos_phot_is_publ_ab53a2_idx')],
            },
        ),
    ]
